# -*- coding: utf-8 -*-
"""Neural networks Lab 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAFfXkNFE1UJrnbvpClsG9Ib_Mf7JaX_
"""

# Commented out IPython magic to ensure Python compatibility.
# Импорт библиотек
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
import os

# Создаем папку для моделей если не существует
os.makedirs('models', exist_ok=True)

# Настройка для корректного отображения графиков
# %matplotlib inline
plt.rcParams['figure.figsize'] = (10, 6)

# ===== ЭТАП 1: Бинарный классификатор IMDB =====

print("=== ЭТАП 1: Бинарный классификатор IMDB ===")

# 1. Загрузка данных IMDB
NUM_WORDS = 15_000
(train_data, train_labels), (test_data, test_labels) = tf.keras.datasets.imdb.load_data(num_words=NUM_WORDS)

print(f"Размер тренировочной выборки: {len(train_data)}")
print(f"Размер тестовой выборки: {len(test_data)}")

# 2-3. Подготовка данных (multi-hot encoding)
def multi_hot_encoding(reviews, num_words):
    results = np.zeros((len(reviews), num_words))
    for i, review in enumerate(reviews):
        for word_index in review:
            if word_index < num_words:
                results[i, word_index] = 1.0
    return results

train_features = multi_hot_encoding(train_data, NUM_WORDS)
test_features = multi_hot_encoding(test_data, NUM_WORDS)

# Проверка сбалансированности классов
positive = sum(train_labels)
negative = len(train_labels) - positive
print(f"Положительные отзывы: {positive}")
print(f"Отрицательные отзывы: {negative}")

# Визуализация распределения классов
plt.figure(figsize=(8, 4))
plt.bar(['Negative', 'Positive'], [negative, positive])
plt.title('Распределение классов в тренировочной выборке')
plt.ylabel('Количество отзывов')
plt.show()

# 4. Создание модели
def create_binary_classifier():
    input = tf.keras.layers.Input(shape=(NUM_WORDS,))
    h1 = tf.keras.layers.Dense(32, activation='relu')(input)
    h2 = tf.keras.layers.Dense(32, activation='tanh')(h1)
    output = tf.keras.layers.Dense(1, activation='sigmoid')(h2)
    return tf.keras.models.Model(inputs=input, outputs=output)

# Базовая модель для сравнения
def create_binary_classifier_base():
    input = tf.keras.layers.Input(shape=(NUM_WORDS,))
    h1 = tf.keras.layers.Dense(16, activation='relu')(input)
    h2 = tf.keras.layers.Dense(16, activation='relu')(h1)
    output = tf.keras.layers.Dense(1, activation='sigmoid')(h2)
    return tf.keras.models.Model(inputs=input, outputs=output)

# СОЗДАЕМ МОДЕЛИ ПЕРЕД КОМПИЛЯЦИЕЙ
model_binary = create_binary_classifier()
model_binary_base = create_binary_classifier_base()

# Вывод архитектуры модели
print("Архитектура основной модели:")
model_binary.summary()

print("\nАрхитектура базовой модели:")
model_binary_base.summary()

# 5. Настройка оптимизатора
model_binary.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3, momentum=0.8, nesterov=True),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_binary_base.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3, momentum=0.8, nesterov=True),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 6-7. Обучение и валидация
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3),
    tf.keras.callbacks.ModelCheckpoint('models/binary_classifier.keras',
                                     monitor='val_loss', save_best_only=True)
]

print("Обучение основной модели...")
history_binary = model_binary.fit(
    train_features, train_labels,
    epochs=150,
    batch_size=512,
    validation_split=0.2,
    callbacks=callbacks,
    verbose=0
)

print("Обучение базовой модели...")
history_binary_base = model_binary_base.fit(
    train_features, train_labels,
    epochs=150,
    batch_size=512,
    validation_split=0.2,
    callbacks=callbacks,
    verbose=0
)

# 8. Тестирование и визуализация
test_loss, test_acc = model_binary.evaluate(test_features, test_labels, verbose=0)
test_loss_base, test_acc_base = model_binary_base.evaluate(test_features, test_labels, verbose=0)

print(f"Основная модель - Точность на тесте: {test_acc:.4f}")
print(f"Базовая модель - Точность на тесте: {test_acc_base:.4f}")

# Визуализация результатов
plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.plot(history_binary.history['accuracy'], label='Основная train')
plt.plot(history_binary.history['val_accuracy'], label='Основная val')
plt.plot(history_binary_base.history['accuracy'], label='Базовая train')
plt.plot(history_binary_base.history['val_accuracy'], label='Базовая val')
plt.title('Точность моделей')
plt.xlabel('Эпоха')
plt.ylabel('Точность')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history_binary.history['loss'], label='Основная train')
plt.plot(history_binary.history['val_loss'], label='Основная val')
plt.plot(history_binary_base.history['loss'], label='Базовая train')
plt.plot(history_binary_base.history['val_loss'], label='Базовая val')
plt.title('Потери моделей')
plt.xlabel('Эпоха')
plt.ylabel('Потери')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

""" ЭТАП 2"""

# ===== ЭТАП 2: Многоклассовый классификатор Reuters =====

print("\n=== ЭТАП 2: Многоклассовый классификатор Reuters ===")

# 1. Загрузка данных Reuters
NUM_WORDS = 10_000
NUM_CLASSES = 46

(train_data, train_labels), (test_data, test_labels) = tf.keras.datasets.reuters.load_data(
    num_words=NUM_WORDS
)

print(f"Размер тренировочной выборки: {len(train_data)}")
print(f"Размер тестовой выборки: {len(test_data)}")
print(f"Количество классов: {NUM_CLASSES}")

# 2-3. Подготовка данных
train_features = multi_hot_encoding(train_data, NUM_WORDS)
test_features = multi_hot_encoding(test_data, NUM_WORDS)

train_labels_categorical = tf.keras.utils.to_categorical(train_labels, NUM_CLASSES)
test_labels_categorical = tf.keras.utils.to_categorical(test_labels, NUM_CLASSES)

# Визуализация распределения классов
plt.figure(figsize=(12, 6))
plt.hist(train_labels, bins=NUM_CLASSES, log=True)
plt.title('Распределение классов в наборе Reuters')
plt.xlabel('Класс')
plt.ylabel('Количество статей (лог. шкала)')
plt.grid(True)
plt.show()

# 4. Создание модели согласно варианту
def create_multiclass_classifier():
    input = tf.keras.layers.Input(shape=(NUM_WORDS,))
    h1 = tf.keras.layers.Dense(16, activation='tanh')(input)
    h2 = tf.keras.layers.Dense(32, activation='relu')(h1)
    output = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(h2)
    return tf.keras.models.Model(inputs=input, outputs=output)

# Базовая модель для сравнения
def create_multiclass_classifier_base():
    input = tf.keras.layers.Input(shape=(NUM_WORDS,))
    h1 = tf.keras.layers.Dense(64, activation='relu')(input)
    h2 = tf.keras.layers.Dense(64, activation='relu')(h1)
    output = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(h2)
    return tf.keras.models.Model(inputs=input, outputs=output)

model_multiclass = create_multiclass_classifier()
model_multiclass_base = create_multiclass_classifier_base()

print("Архитектура основной модели:")
model_multiclass.summary()

# 5. Настройка оптимизатора
model_multiclass.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model_multiclass_base.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 6-7. Обучение и валидация
callbacks_multiclass = [
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=4),
    tf.keras.callbacks.ModelCheckpoint('models/multiclass_classifier.keras',
                                     monitor='val_loss', save_best_only=True)
]

print("Обучение основной модели...")
history_multiclass = model_multiclass.fit(
    train_features, train_labels_categorical,
    epochs=35,
    batch_size=1024,
    validation_split=0.2,
    callbacks=callbacks_multiclass,
    verbose=0
)

print("Обучение базовой модели...")
history_multiclass_base = model_multiclass_base.fit(
    train_features, train_labels_categorical,
    epochs=35,
    batch_size=1024,
    validation_split=0.2,
    callbacks=callbacks_multiclass,
    verbose=0
)

# 8. Тестирование и визуализация
test_loss_multi, test_acc_multi = model_multiclass.evaluate(test_features, test_labels_categorical, verbose=0)
test_loss_multi_base, test_acc_multi_base = model_multiclass_base.evaluate(test_features, test_labels_categorical, verbose=0)

print(f"Основная модель - Точность на тесте: {test_acc_multi:.4f}")
print(f"Базовая модель - Точность на тесте: {test_acc_multi_base:.4f}")

# Визуализация результатов
plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.plot(history_multiclass.history['accuracy'], label='Основная train')
plt.plot(history_multiclass.history['val_accuracy'], label='Основная val')
plt.plot(history_multiclass_base.history['accuracy'], label='Базовая train')
plt.plot(history_multiclass_base.history['val_accuracy'], label='Базовая val')
plt.title('Точность моделей')
plt.xlabel('Эпоха')
plt.ylabel('Точность')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history_multiclass.history['loss'], label='Основная train')
plt.plot(history_multiclass.history['val_loss'], label='Основная val')
plt.plot(history_multiclass_base.history['loss'], label='Базовая train')
plt.plot(history_multiclass_base.history['val_loss'], label='Базовая val')
plt.title('Потери моделей')
plt.xlabel('Эпоха')
plt.ylabel('Потери')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""ЭТАП 3"""

# ===== ЭТАП 3: Регрессионная модель Boston Housing =====

print("\n=== ЭТАП 3: Регрессионная модель Boston Housing ===")

# 1. Загрузка данных Boston Housing
(train_features, train_labels), (test_features, test_labels) = tf.keras.datasets.boston_housing.load_data()

print(f"Размер тренировочной выборки: {train_features.shape}")
print(f"Размер тестовой выборки: {test_features.shape}")

# Описание признаков
feature_names = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS",
    "RAD", "TAX", "PTRATIO", "B", "LSTAT"
]

print("Характеристики признаков тренировочной выборки:")
train_df = pd.DataFrame(train_features, columns=feature_names)
print(train_df.describe())

# 2-3. Подготовка данных (нормализация)
def normalize_data(train_data, test_data):
    mean = train_data.mean(axis=0)
    std = train_data.std(axis=0)
    train_normalized = (train_data - mean) / std
    test_normalized = (test_data - mean) / std
    return train_normalized, test_normalized

train_features_norm, test_features_norm = normalize_data(train_features, test_features)

# Визуализация распределения целевой переменной
plt.figure(figsize=(10, 6))
plt.hist(train_labels, bins=30, alpha=0.7, label='Тренировочная')
plt.hist(test_labels, bins=30, alpha=0.7, label='Тестовая')
plt.title('Распределение цен на дома')
plt.xlabel('Цена ($1000)')
plt.ylabel('Количество')
plt.legend()
plt.grid(True)
plt.show()
print(train_features_norm)

# 4. Создание модели согласно варианту
def create_regression_model():
    input = tf.keras.layers.Input(shape=(13,))
    h1 = tf.keras.layers.Dense(16, activation='tanh')(input)
    h2 = tf.keras.layers.Dense(32, activation='relu')(h1)
    output = tf.keras.layers.Dense(1, activation='linear')(h2)
    return tf.keras.models.Model(inputs=input, outputs=output)

# Базовая модель для сравнения
def create_regression_model_base():
    input = tf.keras.layers.Input(shape=(13,))
    h1 = tf.keras.layers.Dense(64, activation='relu')(input)
    h2 = tf.keras.layers.Dense(64, activation='relu')(h1)
    output = tf.keras.layers.Dense(1, activation='linear')(h2)
    return tf.keras.models.Model(inputs=input, outputs=output)

print("Архитектура основной регрессионной модели:")
create_regression_model().summary()

# 5. Настройка оптимизатора
def compile_model(model):
    model.compile(
        optimizer='rmsprop',
        loss='mse',
        metrics=['mae']
    )
    return model

# 6. Кросс-валидация (K = количество слоев + 1 = 3)
k = 3
kf = KFold(n_splits=k, shuffle=True, random_state=42)

def cross_validate_model(model_creator):
    mae_scores = []

    for fold, (train_index, val_index) in enumerate(kf.split(train_features_norm)):
        print(f"  Обучение fold {fold + 1}...")

        # Разделение данных
        X_train, X_val = train_features_norm[train_index], train_features_norm[val_index]
        y_train, y_val = train_labels[train_index], train_labels[val_index]

        # Создание и компиляция модели
        model = model_creator()
        model = compile_model(model)

        # Обучение
        model.fit(
            X_train, y_train,
            epochs=100,
            batch_size=32,
            validation_data=(X_val, y_val),
            verbose=0
        )

        # Оценка
        _, mae = model.evaluate(X_val, y_val, verbose=0)
        mae_scores.append(mae)
        print(f"  Fold {fold + 1} MAE: {mae:.4f}")

    return mae_scores

print("Кросс-валидация основной модели...")
mae_scores = cross_validate_model(create_regression_model)

print("Кросс-валидация базовой модели...")
mae_scores_base = cross_validate_model(create_regression_model_base)

print(f"Основная модель - MAE кросс-валидация: {np.mean(mae_scores):.4f} (+/- {np.std(mae_scores):.4f})")
print(f"Базовая модель - MAE кросс-валидация: {np.mean(mae_scores_base):.4f} (+/- {np.std(mae_scores_base):.4f})")

# 7-8. Финальное обучение и тестирование
print("Финальное обучение основной модели...")
model_regression = create_regression_model()
model_regression = compile_model(model_regression)

history_regression = model_regression.fit(
    train_features_norm, train_labels,
    epochs=200,
    batch_size=32,
    verbose=0
)

print("Финальное обучение базовой модели...")
model_regression_base = create_regression_model_base()
model_regression_base = compile_model(model_regression_base)

history_regression_base = model_regression_base.fit(
    train_features_norm, train_labels,
    epochs=200,
    batch_size=32,
    verbose=0
)

# Тестирование
test_loss_reg, test_mae_reg = model_regression.evaluate(test_features_norm, test_labels, verbose=0)
test_loss_reg_base, test_mae_reg_base = model_regression_base.evaluate(test_features_norm, test_labels, verbose=0)

print(f"Основная модель - MAE на тесте: {test_mae_reg:.4f}")
print(f"Базовая модель - MAE на тесте: {test_mae_reg_base:.4f}")

# Визуализация результатов регрессии
plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.plot(history_regression.history['loss'], label='Основная train')
plt.plot(history_regression_base.history['loss'], label='Базовая train')
plt.title('MSE моделей')
plt.xlabel('Эпоха')
plt.ylabel('MSE')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history_regression.history['mae'][50:], label='Основная train')
plt.plot(history_regression_base.history['mae'][50:], label='Базовая train')
plt.title('MAE моделей')
plt.xlabel('Эпоха')
plt.ylabel('MAE')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Пример предсказания
sample_idx = 4
prediction = model_regression.predict(np.array([test_features_norm[sample_idx]]), verbose=0)[0, 0]
actual = test_labels[sample_idx]

print(f"\nПример предсказания:")
print(f"Реальная цена: ${actual:.1f}k")
print(f"Предсказанная цена: ${prediction:.1f}k")
print(f"Ошибка: ${abs(actual - prediction):.2f}k")

"""Финальные выводы"""

# ===== ВЫВОДЫ =====

print("\n" + "="*60)
print("ИТОГОВОЕ СРАВНЕНИЕ РЕЗУЛЬТАТОВ")
print("="*60)

print("\nЭТАП 1 - Бинарная классификация IMDB:")
print(f"  Основная модель (16-16 relu-relu): {test_acc:.4f}")
print(f"  Базовая модель (32-32 relu-tanh):  {test_acc_base:.4f}")
print(f"  Разница: {test_acc - test_acc_base:+.4f}")

print("\nЭТАП 2 - Многоклассовая классификация Reuters:")
print(f"  Основная модель (16-32 tanh-relu): {test_acc_multi:.4f}")
print(f"  Базовая модель (64-64 relu-relu):  {test_acc_multi_base:.4f}")
print(f"  Разница: {test_acc_multi - test_acc_multi_base:+.4f}")

print("\nЭТАП 3 - Регрессия Boston Housing:")
print(f"  Основная модель (16-32 tanh-relu): {test_mae_reg:.4f}")
print(f"  Базовая модель (64-64 relu-relu):  {test_mae_reg_base:.4f}")
print(f"  Разница: {test_mae_reg_base - test_mae_reg:+.4f} (меньше - лучше)")

print("\n" + "="*60)
print("ВЫВОД:")
print("Все модели успешно обучены и протестированы. Сравнение с базовыми")
print("моделями показывает, что предложенные архитектуры демонстрируют")
print("сопоставимую или лучшую производительность при меньшем количестве")
print("параметров, что свидетельствует об их эффективности.")
print("="*60)