# -*- coding: utf-8 -*-
"""Untitled75.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDjRq-x29YFshp-TfRt-HB5zl2EvkOsa
"""

# Задание 1. Загрузка и первичный анализ данных

# 1. Импорт библиотек
import pandas as pd
import numpy as np

# 2. Загрузка данных (открытый датасет Titanic с Kaggle)
# Прямая ссылка на raw-файл (можно также скачать локально)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Альтернативно, если файл скачан локально:
# df = pd.read_csv('titanic.csv')

# 3. Первичный анализ

# 3.1. Первые 5 строк
print("=== Первые 5 строк данных ===")
print(df.head())

# 3.2. Типы данных и количество пропусков
print("\n=== Информация о данных (типы, пропуски, память) ===")
print(df.info())

# Более детально по пропускам (в процентах)
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({'Кол-во пропусков': missing, 'Процент': missing_pct})
print("\n=== Пропуски по столбцам ===")
print(missing_df[missing_df['Кол-во пропусков'] > 0])

# 3.3. Сводная статистика по числовым признакам
print("\n=== Сводная статистика (числовые признаки) ===")
print(df.describe())

# 3.4. Поиск дубликатов
duplicates_count = df.duplicated().sum()
print(f"\n=== Количество полных дубликатов строк: {duplicates_count} ===")

# Дополнительно: быстрая проверка аномалий (пример для возраста)
print("\n=== Проверка аномалий (например, возраст Age) ===")
print(f"Минимальный возраст: {df['Age'].min()}")
print(f"Максимальный возраст: {df['Age'].max()}")
print(f"Количество отрицательных значений возраста: {(df['Age'] < 0).sum()}")
print(f"Количество нулевых значений возраста: {(df['Age'] == 0).sum()}")

# Аномалии в Fare (стоимость билета) — не может быть отрицательной
print(f"\nОтрицательная стоимость билета: {(df['Fare'] < 0).sum()}")

# Выбросы по возрасту (например, старше 100 лет — возможно, ошибка)
print(f"Пассажиров старше 100 лет: {(df['Age'] > 100).sum()}")

# Завершение
print("\nПервичный анализ завершён.")