# -*- coding: utf-8 -*-
"""Untitled76.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_OB59A3a6BJmyGi2GdeOP2WZfMRZTcR
"""

# Задание 2. Очистка данных с помощью ИИ инструментов
# Продолжение работы с датасетом Titanic

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# Загрузка данных (ещё раз, чтобы начать с исходных)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df_raw = pd.read_csv(url)
print("Исходные данные загружены. Размер:", df_raw.shape)

# Создадим копии для разных методов обработки
df_python = df_raw.copy()  # для обработки через Python/SimpleImputer
df_excel = df_raw.copy()   # для имитации ручного заполнения в Excel

# ========== 1. ОБРАБОТКА ПРОПУСКОВ ==========

# 1.1. Анализ пропусков перед обработкой
print("\n=== Пропуски до обработки ===")
print(df_python.isnull().sum()[df_python.isnull().sum() > 0])

# 1.2. Разделение признаков на числовые и категориальные
numeric_features = ['Age', 'Fare']
categorical_features = ['Embarked']

# 1.3. Применение SimpleImputer (метод ИИ/автоматический)
# Для числовых - медиана
num_imputer = SimpleImputer(strategy='median')
df_python['Age'] = num_imputer.fit_transform(df_python[['Age']])
df_python['Fare'] = num_imputer.fit_transform(df_python[['Fare']])

# Для категориальных - наиболее частое значение (mode)
cat_imputer = SimpleImputer(strategy='most_frequent')
df_python['Embarked'] = cat_imputer.fit_transform(df_python[['Embarked']]).ravel()

# 1.4. Имитация ручного заполнения в Excel (средним значением для числовых)
df_excel['Age'] = df_excel['Age'].fillna(df_excel['Age'].mean())
df_excel['Fare'] = df_excel['Fare'].fillna(df_excel['Fare'].mean())
df_excel['Embarked'] = df_excel['Embarked'].fillna(df_excel['Embarked'].mode()[0])

# Проверка результатов
print("\n=== Пропуски после обработки (Python/SimpleImputer) ===")
print(df_python[['Age', 'Fare', 'Embarked']].isnull().sum())

print("\n=== Пропуски после обработки (Excel/ручное) ===")
print(df_excel[['Age', 'Fare', 'Embarked']].isnull().sum())

# 1.5. Сравнение методов заполнения
print("\n=== СРАВНЕНИЕ МЕТОДОВ ЗАПОЛНЕНИЯ ===")
comparison_data = {
    'Признак': ['Age', 'Fare', 'Embarked'],
    'Python (медиана/mode)': [
        df_python['Age'].mean(),
        df_python['Fare'].mean(),
        df_python['Embarked'].mode()[0]
    ],
    'Excel (среднее/mode)': [
        df_excel['Age'].mean(),
        df_excel['Fare'].mean(),
        df_excel['Embarked'].mode()[0]
    ],
    'Разница': [
        abs(df_python['Age'].mean() - df_excel['Age'].mean()),
        abs(df_python['Fare'].mean() - df_excel['Fare'].mean()),
        'Совпадает'
    ]
}
comparison_df = pd.DataFrame(comparison_data)
print(comparison_df)

# Визуализация сравнения для Age
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].hist(df_raw['Age'].dropna(), bins=30, alpha=0.5, label='Исходные', color='blue')
axes[0].hist(df_python['Age'], bins=30, alpha=0.5, label='Медиана (Python)', color='green')
axes[0].set_title('Заполнение медианой (Python)')
axes[0].legend()
axes[1].hist(df_raw['Age'].dropna(), bins=30, alpha=0.5, label='Исходные', color='blue')
axes[1].hist(df_excel['Age'], bins=30, alpha=0.5, label='Среднее (Excel)', color='red')
axes[1].set_title('Заполнение средним (Excel)')
axes[1].legend()
plt.suptitle('Сравнение методов заполнения пропусков в Age')
plt.tight_layout()
plt.show()

# ========== 2. УДАЛЕНИЕ ВЫБРОСОВ ==========

# Выбираем числовые признаки для анализа выбросов
features_for_outliers = ['Age', 'Fare']

# 2.1. Визуализация выбросов ДО обработки (boxplot)
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for idx, feature in enumerate(features_for_outliers):
    axes[idx].boxplot(df_python[feature])
    axes[idx].set_title(f'Boxplot - {feature} (до удаления выбросов)')
    axes[idx].set_ylabel(feature)
plt.suptitle('Выбросы в исходных данных')
plt.tight_layout()
plt.show()

# 2.2. Метод IQR для обнаружения выбросов
print("\n=== ВЫБРОСЫ ПО МЕТОДУ IQR ===")
outliers_info = {}
df_clean_iqr = df_python.copy()

for feature in features_for_outliers:
    Q1 = df_python[feature].quantile(0.25)
    Q3 = df_python[feature].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_python[(df_python[feature] < lower_bound) | (df_python[feature] > upper_bound)]
    outliers_count = len(outliers)
    outliers_info[feature] = {
        'Q1': Q1, 'Q3': Q3, 'IQR': IQR,
        'lower_bound': lower_bound, 'upper_bound': upper_bound,
        'outliers_count': outliers_count,
        'outliers_percent': (outliers_count/len(df_python))*100
    }

    print(f"\n{feature}:")
    print(f"  Q1={Q1:.2f}, Q3={Q3:.2f}, IQR={IQR:.2f}")
    print(f"  Границы: [{lower_bound:.2f}, {upper_bound:.2f}]")
    print(f"  Выбросов: {outliers_count} ({outliers_info[feature]['outliers_percent']:.1f}%)")

    # Удаляем выбросы (для метода IQR)
    df_clean_iqr = df_clean_iqr[(df_clean_iqr[feature] >= lower_bound) &
                                 (df_clean_iqr[feature] <= upper_bound)]

print(f"\nРазмер данных после удаления выбросов по IQR: {df_clean_iqr.shape}")

# 2.3. Метод Isolation Forest (ИИ-метод)
print("\n=== МЕТОД ISOLATION FOREST ===")
# Подготовка данных для Isolation Forest (используем те же признаки)
X_outliers = df_python[features_for_outliers].copy()
# Заполним возможные пропуски (хотя их уже нет)
X_outliers = X_outliers.fillna(X_outliers.median())

# Обучение модели
iso_forest = IsolationForest(contamination=0.1, random_state=42)
predictions = iso_forest.fit_predict(X_outliers)

# -1 - выброс, 1 - нормальная точка
outliers_if = df_python[predictions == -1]
df_clean_if = df_python[predictions == 1].copy()

print(f"Выбросов по Isolation Forest: {len(outliers_if)} ({len(outliers_if)/len(df_python)*100:.1f}%)")
print(f"Размер данных после удаления выбросов (IF): {df_clean_if.shape}")

# 2.4. Сравнение результатов двух методов
print("\n=== СРАВНЕНИЕ МЕТОДОВ ОБНАРУЖЕНИЯ ВЫБРОСОВ ===")
comparison_outliers = pd.DataFrame({
    'Признак/Метод': ['IQR - Age', 'IQR - Fare', 'Isolation Forest (общий)'],
    'Количество выбросов': [outliers_info['Age']['outliers_count'],
                            outliers_info['Fare']['outliers_count'],
                            len(outliers_if)],
    'Процент': [outliers_info['Age']['outliers_percent'],
                outliers_info['Fare']['outliers_percent'],
                len(outliers_if)/len(df_python)*100]
})
print(comparison_outliers)

# 2.5. Визуализация ПОСЛЕ удаления выбросов (метод IQR)
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for idx, feature in enumerate(features_for_outliers):
    axes[idx].boxplot(df_clean_iqr[feature])
    axes[idx].set_title(f'Boxplot - {feature} (после IQR)')
    axes[idx].set_ylabel(feature)
plt.suptitle('Данные после удаления выбросов (метод IQR)')
plt.tight_layout()
plt.show()

# ========== 3. СТАНДАРТИЗАЦИЯ ДАННЫХ ==========

# 3.1. Выбираем числовые признаки для стандартизации
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch']
df_for_scaling = df_clean_iqr[numeric_cols].copy()

print("\n=== СТАНДАРТИЗАЦИЯ ДАННЫХ ===")
print("Исходная статистика (до стандартизации):")
print(df_for_scaling.describe())

# 3.2. Применение StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_for_scaling)
df_scaled = pd.DataFrame(scaled_data, columns=numeric_cols)

print("\nСтатистика ПОСЛЕ стандартизации:")
print(df_scaled.describe())
print(f"\nСреднее после стандартизации (должно быть ≈0): {df_scaled.mean().mean():.10f}")
print(f"Стандартное отклонение после стандартизации (должно быть ≈1): {df_scaled.std().mean():.4f}")

# 3.3. Визуализация распределения ДО и ПОСЛЕ масштабирования
fig, axes = plt.subplots(2, 4, figsize=(16, 8))
axes = axes.flatten()

for idx, col in enumerate(numeric_cols):
    # До масштабирования
    axes[idx].hist(df_for_scaling[col], bins=30, alpha=0.7, color='blue', edgecolor='black')
    axes[idx].set_title(f'{col} (ДО стандартизации)')
    axes[idx].set_xlabel(col)
    axes[idx].set_ylabel('Частота')

    # После масштабирования
    axes[idx+4].hist(df_scaled[col], bins=30, alpha=0.7, color='green', edgecolor='black')
    axes[idx+4].set_title(f'{col} (ПОСЛЕ стандартизации)')
    axes[idx+4].set_xlabel('Значение (Z-score)')
    axes[idx+4].set_ylabel('Частота')

plt.suptitle('Сравнение распределений до и после стандартизации', fontsize=14)
plt.tight_layout()
plt.show()

# 3.4. Дополнительная визуализация: ящики с усами до/после
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# До стандартизации
df_for_scaling.boxplot(ax=axes[0])
axes[0].set_title('Распределение признаков ДО стандартизации')
axes[0].set_ylabel('Значения')
axes[0].tick_params(axis='x', rotation=45)

# После стандартизации
df_scaled.boxplot(ax=axes[1])
axes[1].set_title('Распределение признаков ПОСЛЕ стандартизации')
axes[1].set_ylabel('Значения (Z-score)')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# 3.5. Проверка корреляции до и после (стандартизация не влияет на корреляцию)
print("\n=== ВЛИЯНИЕ СТАНДАРТИЗАЦИИ НА КОРРЕЛЯЦИЮ ===")
print("Корреляция ДО стандартизации:")
print(df_for_scaling.corr().round(3))
print("\nКорреляция ПОСЛЕ стандартизации:")
print(df_scaled.corr().round(3))

# Финальный вывод
print("\n" + "="*50)
print("ЗАДАНИЕ 2 ВЫПОЛНЕНО")
print("="*50)
print("1. Пропуски заполнены (медиана/mode для Python, среднее/mode для Excel)")
print("2. Выбросы обнаружены и удалены (IQR и Isolation Forest)")
print("3. Данные стандартизированы (среднее=0, std=1)")