# -*- coding: utf-8 -*-
"""Untitled77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZMnTIBWUvS46pnWbDA_GKA9g14z63Bz
"""

# Задание 3. Преобразование категориальных данных
# Полный готовый код с принтами

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
import re
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Загрузка данных Titanic
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Очистка данных
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Cabin'] = df['Cabin'].fillna('Unknown')

categorical_cols = ['Sex', 'Embarked', 'Pclass']

print("Исходные данные:")
print(df[categorical_cols].head())

# ========== 1. ONE-HOT ENCODING ==========
print("\n" + "="*60)
print("1. ONE-HOT ENCODING (pd.get_dummies)")
print("="*60)

df_onehot = pd.get_dummies(df, columns=categorical_cols, prefix=categorical_cols)
print(f"Размер данных после One-Hot Encoding: {df_onehot.shape}")
print(f"Добавлено новых столбцов: {df_onehot.shape[1] - df.shape[1]}")
print("\nПример One-Hot Encoding (первые 5 строк):")
onehot_sample = df_onehot[[col for col in df_onehot.columns if any(cat in col for cat in ['Sex_', 'Embarked_', 'Pclass_'])]].head()
print(onehot_sample)

# ========== 2. LABEL ENCODER ==========
print("\n" + "="*60)
print("2. LABEL ENCODER (sklearn)")
print("="*60)

df_label = df.copy()
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df_label[col + '_encoded'] = le.fit_transform(df_label[col])
    label_encoders[col] = le
    print(f"\n{col} -> метки:")
    for original, encoded in zip(le.classes_, range(len(le.classes_))):
        print(f"  {original} -> {encoded}")

print("\nПример Label Encoding (первые 5 строк):")
print(df_label[['Sex', 'Sex_encoded', 'Embarked', 'Embarked_encoded', 'Pclass', 'Pclass_encoded']].head())

# ========== 3. ORDINAL ENCODER ==========
print("\n" + "="*60)
print("3. ORDINAL ENCODER (с пользовательским порядком)")
print("="*60)

df_ordinal = df.copy()
df_temp = df.copy()
df_temp['Pclass_str'] = df_temp['Pclass'].astype(str)

ordinal_categories = [
    ['male', 'female'],
    ['C', 'Q', 'S'],
    ['3', '2', '1']
]

ordinal_encoder = OrdinalEncoder(categories=ordinal_categories)
encoded_array = ordinal_encoder.fit_transform(df_temp[['Sex', 'Embarked', 'Pclass_str']])

for i, col in enumerate(['Sex', 'Embarked', 'Pclass']):
    df_ordinal[col + '_ordinal'] = encoded_array[:, i]

print("Пример Ordinal Encoding (первые 5 строк):")
print(df_ordinal[['Sex', 'Sex_ordinal', 'Embarked', 'Embarked_ordinal', 'Pclass', 'Pclass_ordinal']].head())

print("\nСоответствие значений меткам (Ordinal Encoding):")
print("Sex: male->0, female->1")
print("Embarked: C->0, Q->1, S->2")
print("Pclass: 3->0, 2->1, 1->2")

# ========== 4. РУЧНОЕ КОДИРОВАНИЕ ==========
print("\n" + "="*60)
print("4. РУЧНОЕ КОДИРОВАНИЕ (с произвольным порядком)")
print("="*60)

df_manual = df.copy()
custom_mapping = {
    'Sex': {'male': 0, 'female': 1},
    'Embarked': {'C': 0, 'Q': 1, 'S': 2},
    'Pclass': {3: 0, 2: 1, 1: 2}
}
for col, mapping in custom_mapping.items():
    df_manual[col + '_custom_encoded'] = df_manual[col].map(mapping)

print("Ручное кодирование (первые 5 строк):")
print(df_manual[['Sex', 'Sex_custom_encoded', 'Embarked', 'Embarked_custom_encoded', 'Pclass', 'Pclass_custom_encoded']].head())

# ========== 5. СРАВНЕНИЕ МЕТОДОВ ==========
print("\n" + "="*60)
print("5. СРАВНЕНИЕ МЕТОДОВ КОДИРОВАНИЯ (первые 10 строк)")
print("="*60)

comparison_df = pd.DataFrame({
    'PassengerId': df['PassengerId'].head(10),
    'Sex_orig': df['Sex'].head(10),
    'Sex_OneHot_M': df_onehot['Sex_male'].head(10),
    'Sex_OneHot_F': df_onehot['Sex_female'].head(10),
    'Sex_Label': df_label['Sex_encoded'].head(10),
    'Sex_Ordinal': df_ordinal['Sex_ordinal'].head(10).astype(int),
    'Embarked_orig': df['Embarked'].head(10),
    'Emb_OneHot_S': df_onehot['Embarked_S'].head(10),
    'Emb_Label': df_label['Embarked_encoded'].head(10),
    'Emb_Ordinal': df_ordinal['Embarked_ordinal'].head(10).astype(int),
    'Pclass_orig': df['Pclass'].head(10),
    'Pclass_Label': df_label['Pclass_encoded'].head(10),
    'Pclass_Ordinal': df_ordinal['Pclass_ordinal'].head(10).astype(int)
})
print(comparison_df.to_string(index=False))

# ========== 6. ВЛИЯНИЕ НА РАЗМЕР ДАТАСЕТА ==========
print("\n" + "="*60)
print("6. ВЛИЯНИЕ КОДИРОВАНИЯ НА РАЗМЕР ДАТАСЕТА")
print("="*60)

size_comparison = pd.DataFrame({
    'Метод': ['Исходные', 'One-Hot', 'Label', 'Ordinal'],
    'Столбцов': [df.shape[1], df_onehot.shape[1], df_label.shape[1], df_ordinal.shape[1]],
    'Память_MB': [
        df.memory_usage(deep=True).sum() / 1024**2,
        df_onehot.memory_usage(deep=True).sum() / 1024**2,
        df_label.memory_usage(deep=True).sum() / 1024**2,
        df_ordinal.memory_usage(deep=True).sum() / 1024**2
    ]
})
size_comparison['Увеличение_%'] = ((size_comparison['Столбцов'] - df.shape[1]) / df.shape[1] * 100).round(1)
print(size_comparison.to_string(index=False))

# ========== 7. ОБРАБОТКА ТЕКСТОВЫХ ДАННЫХ ==========
print("\n" + "="*60)
print("7. ОБРАБОТКА ТЕКСТОВЫХ ДАННЫХ")
print("="*60)

# Создание текстового датасета
text_data = pd.DataFrame({
    'review_id': [1, 2, 3, 4, 5],
    'review_text': [
        "The movie was absolutely amazing and fantastic! I loved it.",
        "Terrible film, worst movie ever seen. Complete waste of time.",
        "Pretty good, not great but enjoyable. Decent acting.",
        "Amazing experience, wonderful plot, fantastic actors!",
        "Bad acting, boring story, terrible movie overall."
    ],
    'rating': [5, 1, 3, 5, 1]
})

print("Исходные текстовые данные:")
print(text_data[['review_id', 'review_text']])

# Загрузка NLTK ресурсов
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text

def stem_text(text):
    words = clean_text(text).split()
    words = [stemmer.stem(word) for word in words if word not in stop_words]
    return ' '.join(words)

def lemmatize_text(text):
    words = clean_text(text).split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return ' '.join(words)

text_data['cleaned'] = text_data['review_text'].apply(clean_text)
text_data['stemmed'] = text_data['review_text'].apply(stem_text)
text_data['lemmatized'] = text_data['review_text'].apply(lemmatize_text)

print("\nРезультаты стемминга и лемматизации:")
print(text_data[['review_text', 'stemmed', 'lemmatized']])

# Создание дополнительных текстовых признаков
text_data['text_length'] = text_data['review_text'].apply(len)
text_data['word_count'] = text_data['cleaned'].apply(lambda x: len(x.split()))
text_data['avg_word_length'] = (text_data['text_length'] / text_data['word_count']).round(2)

keywords = {
    'positive': ['amazing', 'fantastic', 'wonderful', 'great', 'good', 'love'],
    'negative': ['terrible', 'worst', 'bad', 'boring', 'waste']
}

def count_keywords(text, keywords_list):
    text_lower = text.lower()
    return sum(1 for keyword in keywords_list if keyword in text_lower)

for sentiment, words in keywords.items():
    text_data[f'{sentiment}_keywords_count'] = text_data['review_text'].apply(
        lambda x: count_keywords(x, words)
    )

text_data['sentiment_score'] = text_data['positive_keywords_count'] - text_data['negative_keywords_count']

print("\nИзвлеченные текстовые признаки:")
print(text_data[['review_text', 'text_length', 'word_count', 'avg_word_length',
                 'positive_keywords_count', 'negative_keywords_count', 'sentiment_score']])

# ========== 8. ИТОГОВАЯ ТАБЛИЦА ДЛЯ ОТЧЕТА ==========
print("\n" + "="*60)
print("8. ИТОГОВАЯ СВОДНАЯ ТАБЛИЦА (первые 10 строк)")
print("="*60)

final_summary = pd.DataFrame({
    'PassId': df['PassengerId'].head(10),
    'Sex': df['Sex'].head(10),
    'Sex_OneHot': df_onehot['Sex_male'].head(10),
    'Sex_Label': df_label['Sex_encoded'].head(10),
    'Sex_Ordinal': df_ordinal['Sex_ordinal'].head(10).astype(int),
    'Embarked': df['Embarked'].head(10),
    'Emb_OneHot_S': df_onehot['Embarked_S'].head(10),
    'Emb_Label': df_label['Embarked_encoded'].head(10),
    'Pclass': df['Pclass'].head(10),
    'Pclass_Label': df_label['Pclass_encoded'].head(10)
})
print(final_summary.to_string(index=False))

print("\n" + "="*60)
print("ВЫПОЛНЕНИЕ ЗАДАНИЯ 3 ЗАВЕРШЕНО")
print("="*60)