# -*- coding: utf-8 -*-
"""Untitled78.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNSPsWruIkwUf11x16-UPxz0sx8DVq9G
"""

# Задание 4. Автоматизация предобработки через Pipeline
# Полный готовый код

import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import IsolationForest
from sklearn.base import BaseEstimator, TransformerMixin
import pickle
import joblib

# Загрузка данных
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print("Исходные данные:")
print(f"Размер: {df.shape}")
print(f"Колонки: {df.columns.tolist()}")
print("\nПервые 5 строк:")
print(df.head())

# ========== 1. СОЗДАНИЕ ПОЛЬЗОВАТЕЛЬСКОГО ТРАНСФОРМЕРА ДЛЯ УДАЛЕНИЯ ВЫБРОСОВ ==========

class OutlierRemover(BaseEstimator, TransformerMixin):
    """
    Удаление выбросов методом IQR для числовых признаков
    """
    def __init__(self, features=None, multiplier=1.5):
        self.features = features
        self.multiplier = multiplier
        self.lower_bounds_ = {}
        self.upper_bounds_ = {}

    def fit(self, X, y=None):
        if self.features is None:
            self.features = X.select_dtypes(include=[np.number]).columns.tolist()

        for feature in self.features:
            Q1 = X[feature].quantile(0.25)
            Q3 = X[feature].quantile(0.75)
            IQR = Q3 - Q1
            self.lower_bounds_[feature] = Q1 - self.multiplier * IQR
            self.upper_bounds_[feature] = Q3 + self.multiplier * IQR

        return self

    def transform(self, X, y=None):
        X_copy = X.copy()
        mask = pd.Series([True] * len(X_copy))

        for feature in self.features:
            feature_mask = (X_copy[feature] >= self.lower_bounds_[feature]) & \
                           (X_copy[feature] <= self.upper_bounds_[feature])
            mask = mask & feature_mask

        return X_copy[mask].reset_index(drop=True)

# ========== 2. РАЗДЕЛЕНИЕ ПРИЗНАКОВ ПО ТИПАМ ==========

# Определяем числовые и категориальные признаки
numeric_features = ['Age', 'Fare', 'SibSp', 'Parch']
categorical_features = ['Sex', 'Embarked', 'Pclass']

# ========== 3. СОЗДАНИЕ ТРАНСФОРМЕРОВ ДЛЯ РАЗНЫХ ТИПОВ ДАННЫХ ==========

# Трансформер для числовых признаков: заполнение медианой + масштабирование
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Трансформер для категориальных признаков: заполнение модой + one-hot кодирование
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(drop='first', sparse_output=False))
])

# ========== 4. ОБЪЕДИНЕНИЕ ТРАНСФОРМЕРОВ В ColumnTransformer ==========

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='drop'  # остальные колонки удаляем
)

# ========== 5. СОЗДАНИЕ ПОЛНОГО PIPELINE С УДАЛЕНИЕМ ВЫБРОСОВ ==========

# Сначала удаляем выбросы, затем применяем предобработку
full_pipeline = Pipeline(steps=[
    ('outlier_remover', OutlierRemover(features=numeric_features, multiplier=1.5)),
    ('preprocessor', preprocessor)
])

print("\n" + "="*60)
print("СТРУКТУРА PIPELINE")
print("="*60)
print(full_pipeline)

# ========== 6. ПРИМЕНЕНИЕ PIPELINE К ДАТАСЕТУ ==========

print("\n" + "="*60)
print("ПРИМЕНЕНИЕ PIPELINE К ДАННЫМ")
print("="*60)

# Применяем pipeline для предобработки данных
try:
    # Сначала проверяем на исходных данных
    df_processed = full_pipeline.fit_transform(df)

    print("Pipeline успешно выполнен!")
    print(f"\nРазмер данных ДО обработки: {df.shape}")
    print(f"Размер данных ПОСЛЕ обработки: {df_processed.shape}")

    # Проверяем типы и статистику после обработки
    print(f"\nТип выходных данных: {type(df_processed)}")
    print(f"Количество признаков после обработки: {df_processed.shape[1]}")

    # Показываем первые 5 строк обработанных данных
    print("\nПервые 5 строк после обработки:")
    # Получаем имена признаков после one-hot кодирования
    cat_features_encoded = []
    for i, cat in enumerate(categorical_features):
        if cat == 'Sex':
            cat_features_encoded.append('Sex_male')
        elif cat == 'Embarked':
            cat_features_encoded.extend(['Embarked_Q', 'Embarked_S'])
        elif cat == 'Pclass':
            cat_features_encoded.extend(['Pclass_2', 'Pclass_3'])

    all_features = numeric_features + cat_features_encoded
    df_result = pd.DataFrame(df_processed, columns=all_features)
    print(df_result.head())

    # Статистика после масштабирования
    print("\nСтатистика после обработки (должна быть mean≈0, std≈1 для числовых):")
    print(df_result[numeric_features].describe().round(3))

except Exception as e:
    print(f"Ошибка при выполнении pipeline: {e}")

# ========== 7. ПРОВЕРКА ОТСУТСТВИЯ ОШИБОК С РАЗНЫМИ ДАННЫМИ ==========

print("\n" + "="*60)
print("ПРОВЕРКА PIPELINE НА НОВЫХ ДАННЫХ")
print("="*60)

# Создаём тестовые данные (новые пассажиры)
test_data = pd.DataFrame({
    'Age': [25, 35, np.nan, 50, 18],
    'Fare': [50, 100, 30, np.nan, 20],
    'SibSp': [0, 1, 0, 2, 0],
    'Parch': [0, 0, 1, 1, 0],
    'Sex': ['male', 'female', 'male', 'female', 'male'],
    'Embarked': ['S', 'C', 'Q', np.nan, 'S'],
    'Pclass': [1, 2, 3, 1, 2],
    'Name': ['Test1', 'Test2', 'Test3', 'Test4', 'Test5']
})

print("Тестовые данные (5 новых пассажиров):")
print(test_data[['Age', 'Fare', 'Sex', 'Embarked', 'Pclass']])

# Применяем pipeline к тестовым данным
try:
    test_processed = full_pipeline.transform(test_data)
    print(f"\nТестовые данные успешно обработаны!")
    print(f"Размер после обработки: {test_processed.shape}")

    test_df = pd.DataFrame(test_processed, columns=all_features)
    print("\nОбработанные тестовые данные:")
    print(test_df)
    print("\n✅ Pipeline работает корректно, ошибок нет")

except Exception as e:
    print(f"❌ Ошибка: {e}")

# ========== 8. СОХРАНЕНИЕ ОБУЧЕННОГО PIPELINE ==========

print("\n" + "="*60)
print("СОХРАНЕНИЕ PIPELINE")
print("="*60)

# Сохранение в формате pickle
with open('preprocessing_pipeline.pkl', 'wb') as f:
    pickle.dump(full_pipeline, f)
print("✅ Pipeline сохранён в файл: preprocessing_pipeline.pkl")

# Сохранение в формате joblib (рекомендуется для больших моделей)
joblib.dump(full_pipeline, 'preprocessing_pipeline.joblib')
print("✅ Pipeline сохранён в файл: preprocessing_pipeline.joblib")

# Сохранение также в сжатом формате
joblib.dump(full_pipeline, 'preprocessing_pipeline_compressed.joblib', compress=3)
print("✅ Pipeline сохранён в сжатом формате: preprocessing_pipeline_compressed.joblib")

# ========== 9. ПРОВЕРКА ЗАГРУЗКИ СОХРАНЁННОГО PIPELINE ==========

print("\n" + "="*60)
print("ПРОВЕРКА ЗАГРУЗКИ СОХРАНЁННОГО PIPELINE")
print("="*60)

# Загружаем pipeline из pickle
with open('preprocessing_pipeline.pkl', 'rb') as f:
    loaded_pipeline_pkl = pickle.load(f)
print("✅ Pipeline загружен из pickle")

# Загружаем pipeline из joblib
loaded_pipeline_joblib = joblib.load('preprocessing_pipeline.joblib')
print("✅ Pipeline загружен из joblib")

# Проверяем, что загруженный pipeline работает
test_loaded = loaded_pipeline_pkl.transform(test_data)
print(f"Загруженный pipeline обработал данные: {test_loaded.shape}")

print("\n" + "="*60)
print("ВЫПОЛНЕНИЕ ЗАДАНИЯ 4 ЗАВЕРШЕНО")
print("="*60)

from google.colab import files
files.download('preprocessing_pipeline.joblib')