# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWrj2ZdA8bXPB4kM6vDhg7WieNiPwRrf
"""

# Задание 5. Визуализация результатов обработки
# Полный готовый код

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import IsolationForest
from sklearn.base import BaseEstimator, TransformerMixin

# Установка стиля для графиков
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 12

# Загрузка данных
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Очистка данных (базовая)
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

print("Исходные данные загружены")
print(f"Размер данных: {df.shape}")
print(f"Колонки: {df.columns.tolist()}")

# ========== 1. ОПРЕДЕЛЕНИЕ КЛЮЧЕВЫХ ПРИЗНАКОВ ==========
key_features = ['Age', 'Fare', 'SibSp', 'Parch']
categorical_features = ['Sex', 'Pclass']

# ========== 2. ПРИМЕНЕНИЕ ОБРАБОТКИ ДЛЯ ВИЗУАЛИЗАЦИИ ==========

# Создаём обработанную версию данных
df_processed = df.copy()

# Масштабирование числовых признаков
scaler = StandardScaler()
df_processed[key_features] = scaler.fit_transform(df_processed[key_features])

# One-hot кодирование
df_processed = pd.get_dummies(df_processed, columns=['Sex'], prefix='Sex', drop_first=True)
df_processed['Pclass'] = df_processed['Pclass'].astype('category')

print("\nДанные после обработки:")
print(f"Размер: {df_processed.shape}")

# ========== 3. ТЕПЛОВАЯ КАРТА КОРРЕЛЯЦИИ ДО ОБРАБОТКИ ==========
print("\n" + "="*60)
print("1. ПОСТРОЕНИЕ ТЕПЛОВЫХ КАРТ КОРРЕЛЯЦИИ")
print("="*60)

# Выбираем числовые признаки для корреляции
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'Survived']
if 'Pclass' in df.columns:
    numeric_cols.append('Pclass')

df_numeric_before = df[numeric_cols].copy()
corr_before = df_numeric_before.corr()

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# Heatmap ДО обработки
mask = np.triu(np.ones_like(corr_before, dtype=bool))
sns.heatmap(corr_before,
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8},
            mask=mask,
            ax=axes[0])
axes[0].set_title('Корреляционная матрица\nДО обработки данных', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Признаки', fontsize=12)
axes[0].set_ylabel('Признаки', fontsize=12)

# Heatmap ПОСЛЕ обработки (после масштабирования и кодирования)
# Для после обработки используем те же признаки + закодированный Sex
processed_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'Survived', 'Sex_male']
df_processed_numeric = df_processed[processed_cols].copy()
df_processed_numeric['Pclass'] = df['Pclass']  # добавляем Pclass как числовой

corr_after = df_processed_numeric.corr()

sns.heatmap(corr_after,
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8},
            mask=np.triu(np.ones_like(corr_after, dtype=bool)),
            ax=axes[1])
axes[1].set_title('Корреляционная матрица\nПОСЛЕ обработки данных', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Признаки', fontsize=12)
axes[1].set_ylabel('Признаки', fontsize=12)

plt.tight_layout()
plt.savefig('correlation_heatmap_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: correlation_heatmap_comparison.png")

# ========== 4. PAIRPLOT ДЛЯ КЛЮЧЕВЫХ ПРИЗНАКОВ ==========
print("\n" + "="*60)
print("2. PAIRPLOT ДЛЯ КЛЮЧЕВЫХ ПРИЗНАКОВ")
print("="*60)

# Выбираем 4 ключевых признака + целевая переменная
pairplot_features = ['Age', 'Fare', 'SibSp', 'Survived']

# Pairplot ДО обработки
df_before_pair = df[pairplot_features].copy()
df_before_pair['Pclass'] = df['Pclass']
df_before_pair['Survived'] = df_before_pair['Survived'].astype('category')

fig = plt.figure(figsize=(14, 12))
g = sns.pairplot(df_before_pair,
                 hue='Survived',
                 vars=['Age', 'Fare', 'SibSp', 'Pclass'],
                 palette={0: 'red', 1: 'green'},
                 diag_kind='kde',
                 plot_kws={'alpha': 0.6, 's': 30},
                 diag_kws={'fill': True})
g.fig.suptitle('Pairplot ключевых признаков\nДО обработки данных', fontsize=16, fontweight='bold', y=1.02)
plt.savefig('pairplot_before.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: pairplot_before.png")

# Pairplot ПОСЛЕ обработки (масштабированные данные)
df_after_pair = pd.DataFrame()
df_after_pair['Age_scaled'] = df_processed['Age']
df_after_pair['Fare_scaled'] = df_processed['Fare']
df_after_pair['SibSp_scaled'] = df_processed['SibSp']
df_after_pair['Pclass'] = df['Pclass']
df_after_pair['Survived'] = df['Survived'].astype('category')

fig = plt.figure(figsize=(14, 12))
g = sns.pairplot(df_after_pair,
                 hue='Survived',
                 vars=['Age_scaled', 'Fare_scaled', 'SibSp_scaled', 'Pclass'],
                 palette={0: 'red', 1: 'green'},
                 diag_kind='kde',
                 plot_kws={'alpha': 0.6, 's': 30},
                 diag_kws={'fill': True})
g.fig.suptitle('Pairplot ключевых признаков\nПОСЛЕ обработки (масштабирование)', fontsize=16, fontweight='bold', y=1.02)
plt.savefig('pairplot_after.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: pairplot_after.png")

# ========== 5. KDE ГРАФИКИ ДЛЯ СРАВНЕНИЯ РАСПРЕДЕЛЕНИЙ ==========
print("\n" + "="*60)
print("3. KDE ГРАФИКИ СРАВНЕНИЯ РАСПРЕДЕЛЕНИЙ")
print("="*60)

# Создаём графики для каждого ключевого признака
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

features_for_kde = ['Age', 'Fare', 'SibSp', 'Parch']
titles = ['Возраст (Age)', 'Стоимость билета (Fare)', 'Количество сиблингов/супругов (SibSp)', 'Количество родителей/детей (Parch)']

for i, (feature, title) in enumerate(zip(features_for_kde, titles)):
    # KDE до обработки (исходные данные)
    axes[i].hist(df[feature].dropna(), bins=30, density=True, alpha=0.5,
                 color='blue', label='До обработки (исходные)', edgecolor='black')
    sns.kdeplot(df[feature].dropna(), color='blue', linewidth=2, ax=axes[i])

    # KDE после обработки (масштабированные данные)
    axes[i].hist(df_processed[feature], bins=30, density=True, alpha=0.5,
                 color='green', label='После обработки (масштабированные)', edgecolor='black')
    sns.kdeplot(df_processed[feature], color='green', linewidth=2, ax=axes[i])

    axes[i].set_title(f'Распределение: {title}', fontsize=12, fontweight='bold')
    axes[i].set_xlabel('Значение', fontsize=10)
    axes[i].set_ylabel('Плотность', fontsize=10)
    axes[i].legend(loc='upper right')
    axes[i].grid(True, alpha=0.3)

plt.suptitle('Сравнение распределений признаков ДО и ПОСЛЕ масштабирования',
             fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('kde_comparison_all.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: kde_comparison_all.png")

# ========== 6. ДЕТАЛЬНЫЙ KDE ГРАФИК ДЛЯ AGE И FARE ==========
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# KDE для Age
sns.kdeplot(df['Age'].dropna(), label='До обработки (исходный)',
            color='blue', linewidth=2.5, ax=axes[0])
sns.kdeplot(df_processed['Age'], label='После обработки (масштабированный)',
            color='green', linewidth=2.5, ax=axes[0])
axes[0].axvline(df['Age'].mean(), color='blue', linestyle='--', alpha=0.7, label=f'Среднее исходное: {df["Age"].mean():.1f}')
axes[0].axvline(df_processed['Age'].mean(), color='green', linestyle='--', alpha=0.7, label=f'Среднее после: {df_processed["Age"].mean():.2f}')
axes[0].set_title('Распределение возраста (Age)\nДо и после StandardScaler', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Возраст (лет) / Z-score', fontsize=10)
axes[0].set_ylabel('Плотность', fontsize=10)
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# KDE для Fare
sns.kdeplot(df['Fare'].dropna(), label='До обработки (исходный)',
            color='blue', linewidth=2.5, ax=axes[1])
sns.kdeplot(df_processed['Fare'], label='После обработки (масштабированный)',
            color='green', linewidth=2.5, ax=axes[1])
axes[1].axvline(df['Fare'].mean(), color='blue', linestyle='--', alpha=0.7, label=f'Среднее исходное: {df["Fare"].mean():.1f}')
axes[1].axvline(df_processed['Fare'].mean(), color='green', linestyle='--', alpha=0.7, label=f'Среднее после: {df_processed["Fare"].mean():.2f}')
axes[1].set_title('Распределение стоимости билета (Fare)\nДо и после StandardScaler', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Стоимость / Z-score', fontsize=10)
axes[1].set_ylabel('Плотность', fontsize=10)
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.suptitle('KDE графики: сравнение исходных и масштабированных данных',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('kde_age_fare_detailed.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: kde_age_fare_detailed.png")

# ========== 7. BOXPLOT ДЛЯ ВИЗУАЛИЗАЦИИ ВЫБРОСОВ ДО/ПОСЛЕ ==========
print("\n" + "="*60)
print("4. BOXPLOT ДЛЯ ВИЗУАЛИЗАЦИИ ВЫБРОСОВ")
print("="*60)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Boxplot ДО обработки
df_before_box = df[['Age', 'Fare', 'SibSp', 'Parch']].copy()
df_before_box.boxplot(ax=axes[0])
axes[0].set_title('Boxplot признаков\nДО обработки', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Значения', fontsize=10)
axes[0].tick_params(axis='x', rotation=45)

# Boxplot ПОСЛЕ обработки
df_after_box = df_processed[['Age', 'Fare', 'SibSp', 'Parch']].copy()
df_after_box.boxplot(ax=axes[1])
axes[1].set_title('Boxplot признаков\nПОСЛЕ масштабирования', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Z-score', fontsize=10)
axes[1].tick_params(axis='x', rotation=45)

plt.suptitle('Сравнение масштабов признаков до и после StandardScaler',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('boxplot_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: boxplot_comparison.png")

# ========== 8. СВОДНЫЙ ГРАФИК ВСЕХ ПРИЗНАКОВ ==========
print("\n" + "="*60)
print("5. СВОДНЫЙ ГРАФИК РАСПРЕДЕЛЕНИЙ")
print("="*60)

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
axes = axes.flatten()

for i, feature in enumerate(features_for_kde):
    # Исходное распределение
    axes[i].hist(df[feature].dropna(), bins=30, density=True, alpha=0.6,
                 color='blue', edgecolor='black')
    sns.kdeplot(df[feature].dropna(), color='darkblue', linewidth=2, ax=axes[i])
    axes[i].set_title(f'{feature} (исходный)', fontsize=11, fontweight='bold')
    axes[i].set_xlabel('Значение', fontsize=9)
    axes[i].set_ylabel('Плотность', fontsize=9)
    axes[i].grid(True, alpha=0.3)

    # Масштабированное распределение
    axes[i+4].hist(df_processed[feature], bins=30, density=True, alpha=0.6,
                   color='green', edgecolor='black')
    sns.kdeplot(df_processed[feature], color='darkgreen', linewidth=2, ax=axes[i+4])
    axes[i+4].set_title(f'{feature} (масштабированный)', fontsize=11, fontweight='bold')
    axes[i+4].set_xlabel('Z-score', fontsize=9)
    axes[i+4].set_ylabel('Плотность', fontsize=9)
    axes[i+4].grid(True, alpha=0.3)

plt.suptitle('Сравнение распределений: исходные vs масштабированные данные',
             fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('all_distributions_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ График сохранён: all_distributions_comparison.png")

print("\n" + "="*60)
print("ВЫПОЛНЕНИЕ ЗАДАНИЯ 5 ЗАВЕРШЕНО")
print("="*60)