# -*- coding: utf-8 -*-
"""Lab 1 Computer graphics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xN0UIQERXAyMYrO-EUFv3VNIPnIcaqsj
"""

import customtkinter
import module1

# Настройка вида интерфейса приложения
customtkinter.set_appearance_mode("dark")
customtkinter.set_default_color_theme("blue")

# Создаем окошко приложения и его размер
root = customtkinter.CTk()
root.geometry("600x400")

# Создаем фрейм для отображения информации и остальных частей приложения
frame = customtkinter.CTkFrame(master=root)
frame.pack(pady=20,padx=60, fill="both", expand=True)

#Размещение элементов на фрейме

labela=customtkinter.CTkLabel(master=frame, text = "parameter a value1")
labela.pack(pady=10, padx=10)

entrya=customtkinter.CTkEntry(master=frame, placeholder_text="Enter parameter value1")
entrya.pack(pady=10, padx=10)

labelA=customtkinter.CTkLabel(master=frame, text = "parameter a value2")
labelA.pack(pady=10, padx=10)

entryA=customtkinter.CTkEntry(master=frame, placeholder_text="Enter parameter value2")
entryA.pack(pady=10, padx=10)

labelB=customtkinter.CTkLabel(master=frame, text = "parameter a value3")
labelB.pack(pady=10, padx=10)

entryB=customtkinter.CTkEntry(master=frame, placeholder_text="Enter parameter value3")
entryB.pack(pady=10, padx=10)

# Создание функции, которая будет отрабатывать при нажатии кнопки
def DoIt():
    value1=float(entrya.get())
    value2=float(entryA.get())
    value3=float(entryB.get())

    module1.doit(value1, value2, value3)

# Создание кнопки(задаем функцию, которую она выполняет при помощи параметра command)
button=customtkinter.CTkButton(master=frame, text="Do it", command=DoIt)
button.pack(pady=10, padx=10)

# Запуск цикла
root.mainloop()

import numpy as np
import matplotlib.pyplot as plt

# Задаем функции x(t) и y(t)
def x(a, t):
    return 3 * a * t / (1 + t**3)

def y(a, t):
    return 3 * a * t**2 / (1 + t**3)

def doit(a, A, B):
      # Создаем массив значений t в заданном диапазоне
      t = np.linspace(A, B, 100)

      # Вычисляем значения x и y для каждого значения t
      x_value = x(a, t)
      y_value = y(a, t)

      # Строим график
      plt.plot(x_value, y_value)

      plt.xlabel('x')
      plt.ylabel('y')
      plt.title('x = 3at/(1+t^3), y = 3at^2/(1+t^3)')
      plt.grid(True)
      plt.show()