# -*- coding: utf-8 -*-
"""Lab 2 Lab 3 Computer graphics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqZXDAwsJJLzP-5jCuwc4ZFKcQEAxslF
"""

import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

if __name__ == "__main__":

        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')

        vertices = np.array([
                [3, 0, 0],
                [-3, 0, 0],
                [0, 3, 0],
                [0, -3, 0],
                [0, 0, 3],
                [0, 0, -3]])

        faces = np.array([
                [0, 2, 4],
                [0, 4, 3],
                [0, 3, 5],
                [0, 5, 2],
                [1, 2, 4],
                [1, 4, 3],
                [1, 3, 5],
                [1, 5, 2]])

        print(vertices)

        oktrd = [Poly3DCollection([vertices[face] for face in faces], alpha=1, facecolor='red', edgecolor='k')]
        ax.add_collection3d(oktrd[0])

        ax.auto_scale_xyz([-5, 5], [-5, 5], [-5, 5])

        plt.show()