# -*- coding: utf-8 -*-
"""Lab 7 Computer graphics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOG6XFVIDJZ6CKBnW7PfS9_N1Tpo_Fhf
"""

import matplotlib.pyplot as plt
import numpy as np

def bezier_curve(points, t):
    p0, p1, p2, p3 = points
    u = 1 - t
    u2 = u * u
    u3 = u2 * u
    t2 = t * t
    t3 = t2 * t

    x = (u3 * p0[0] +
         3 * u2 * t * p1[0] +
         3 * u * t2 * p2[0] +
         t3 * p3[0])

    y = (u3 * p0[1] +
         3 * u2 * t * p1[1] +
         3 * u * t2 * p2[1] +
         t3 * p3[1])

    return x, y

# Управляющие точки
control_points = [(50, 200),   # P0
                  (150, 50),   # P1
                  (250, 350),  # P2
                  (350, 200),  # P3
                  (450, 200),  # P4
                  (550, 350)]  # P5

# Параметр t для построения кривой
t_values = np.linspace(0, 1, 100)

# Координаты точек на кривой Безье
curve_points = [bezier_curve(control_points[:4], t) for t in t_values]
curve_points += [bezier_curve(control_points[2:], t) for t in t_values]

# Рисуем управляющие точки
plt.scatter(*zip(*control_points), color='red')

# Рисуем кривую Безье
plt.plot(*zip(*curve_points), color='blue')

# Настройки графика
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Bezier Curve')
plt.grid(True)

# Отображаем график
plt.show()