# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188FucReWI2Mnk5uzHezLdG9zpw4FWB2K
"""

stack = []
input_str = input()

for i in input_str:
    if i not in ('1', '0'):
        print(f"Встретили некорректный символ {i}")
        exit(0)

cntr = 0
print(f"Шаг {cntr}")
print("Состояние: q0")
print(f"Стэк: {stack}\n")

for i in input_str:
    cntr += 1
    if i == '1':
        if stack.__len__() == 0 or stack[-1] == "A":
            stack.append("A")
        else:
            del stack[-1]
    elif i == '0':
        if stack.__len__() == 0 or stack[-1] == "B":
            stack.append("B")
        else:
            del stack[-1]

    print(f"Шаг {cntr}")
    if stack.__len__() == 0:
        print("Состояние: q0")
    elif stack[-1] == "A":
        print("Состояние: q1")
    else:
        print("Состояние: q2")
    print(f"Стэк: {stack}\n")

if stack.__len__() == 0 or stack[-1] == "A":
    print("Допускается")
else:
    print("Не допускается")