# -*- coding: utf-8 -*-
"""Untitled68.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIdc69WYHLo0dJI8_HXgGuvRApI7sCxP
"""

states = ["q0", "q1", "q2", "q3"]
valid_states = ["q3"]
alphabet = "01"

state_changes = {"q0": {"0": "q0", "1": "q1"}, "q1": {"0": "q1", "1": "q2"}, "q2": {"0": "q2", "1": "q3"}, "q3": {"0": "q3", "1": "q3"}}

current_state = "q0"
for input_char in input():
    if input_char not in alphabet:
        print(f"Введен некорректный символ '{input_char}'")
        break
    current_state = state_changes[current_state][input_char]
else:
    print(current_state in valid_states)