# -*- coding: utf-8 -*-
"""Untitled71.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181YRrbGTcNkbYvwwppQNFYhC3h2f3ESV
"""

"""
Лабораторная работа №4
Исследование временной сложности

Язык: TRIANGLE = {⟨G⟩ : G — неориентированный граф, содержащий 3-клику}

Описание МТ:
  Вход: матрица смежности графа G размера n×n на ленте.
  Алгоритм (детерминированная МТ):
    1. Перебрать все тройки вершин (i, j, k), где 0 ≤ i < j < k < n.
    2. Для каждой тройки проверить наличие рёбер (i,j), (j,k), (i,k).
    3. Если все три ребра есть — принять (ACCEPT).
    4. Если ни одна тройка не образует треугольник — отвергнуть (REJECT).

  Число троек: C(n,3) = n(n-1)(n-2)/6.
  Каждая проверка — O(1) обращений к матрице смежности.
  Итого временная сложность: O(n³).

Теоретическая оценка шагов МТ:
  T(n) ≈ c · n³, где c — константа (≈ 1/6 для полного перебора).
"""

import time
import matplotlib.pyplot as plt

# --- Реализация МТ ---

def has_triangle(adj, n):
    """
    Моделирует работу МТ: перебирает все тройки вершин,
    проверяет наличие треугольника. Возвращает (результат, число_шагов).
    """
    steps = 0
    for i in range(n):
        for j in range(i + 1, n):
            for k in range(j + 1, n):
                steps += 1
                if adj[i][j] and adj[j][k] and adj[i][k]:
                    return True, steps
    return False, steps

# --- Генерация графов ---

def graph_without_triangle(n):
    """Двудольный граф (гарантированно без треугольников)."""
    adj = [[False] * n for _ in range(n)]
    half = n // 2
    for i in range(half):
        for j in range(half, n):
            adj[i][j] = adj[j][i] = True
    return adj

def complete_graph(n):
    """Полный граф (треугольник найдётся на первом шаге)."""
    return [[i != j for j in range(n)] for i in range(n)]

# --- Теоретическая оценка ---

def theoretical_steps(n):
    """C(n,3) — worst-case число шагов."""
    return n * (n - 1) * (n - 2) // 6

def visualization(sizes, worst_steps, worst_theory, worst_times):
    # --- Визуализация ---
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    # График 1: факт vs теория (worst-case)
    ax = axes[0]
    ax.plot(sizes, worst_steps, 'ro-', label='Факт. шаги')
    ax.plot(sizes, worst_theory, 'b--s', label='C(n,3) = n(n−1)(n−2)/6')
    ax.set_xlabel('n (число вершин)')
    ax.set_ylabel('Число шагов')
    ax.set_title('Worst-case: факт vs теория')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # График 2: шаги/n³ → константа
    ax = axes[1]
    ratios = [s / (n ** 3) for s, n in zip(worst_steps, sizes)]
    ax.plot(sizes, ratios, 'go-', linewidth=2)
    ax.axhline(y=1 / 6, color='r', linestyle='--', label='1/6 ≈ 0.1667')
    ax.set_xlabel('n (число вершин)')
    ax.set_ylabel('Шаги / n³')
    ax.set_title('Шаги/n³ → const (подтверждение O(n³))')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # График 3: время выполнения
    ax = axes[2]
    ax.plot(sizes, worst_times, 'mo-', label='Время (мс)')
    # Нормируем теоретическую кривую по последней точке
    c = worst_times[-1] / (sizes[-1] ** 3)
    theory_time = [c * n ** 3 for n in sizes]
    ax.plot(sizes, theory_time, 'b--s', label=f'c·n³ (c={c:.2e})')
    ax.set_xlabel('n (число вершин)')
    ax.set_ylabel('Время (мс)')
    ax.set_title('Время выполнения vs c·n³')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('lab4_triangle_plot.png', dpi=150)
    print(f"\nГрафик сохранён: lab4_triangle_plot.png")
    plt.show()

# --- Тесты и визуализация ---

def run_tests():
    sizes = [10, 20, 40, 60, 80, 100, 150, 200]

    # --- Тест 1: worst-case (без треугольников) ---
    worst_steps = []
    worst_theory = []
    worst_times = []

    print("=" * 72)
    print("ТЕСТ 1: Worst-case (двудольный граф, без треугольников)")
    print("-" * 72)
    print(f"{'n':>5} | {'Факт.шаги':>11} | {'C(n,3)':>11} | {'Факт/C(n,3)':>11} | {'Время,мс':>9}")
    print("-" * 72)

    for n in sizes:
        adj = graph_without_triangle(n)
        t0 = time.perf_counter()
        result, steps = has_triangle(adj, n)
        dt = (time.perf_counter() - t0) * 1000
        th = theoretical_steps(n)
        worst_steps.append(steps)
        worst_theory.append(th)
        worst_times.append(dt)
        print(f"{n:>5} | {steps:>11} | {th:>11} | {steps/th:>11.4f} | {dt:>9.2f}")

    # --- Тест 2: best-case (полный граф) ---
    best_steps = []

    print()
    print("=" * 72)
    print("ТЕСТ 2: Best-case (полный граф, треугольник сразу)")
    print("-" * 72)
    print(f"{'n':>5} | {'Факт.шаги':>11} | {'C(n,3)':>11} | {'Результат':>10}")
    print("-" * 72)

    for n in sizes:
        adj = complete_graph(n)
        result, steps = has_triangle(adj, n)
        best_steps.append(steps)
        print(f"{n:>5} | {steps:>11} | {theoretical_steps(n):>11} | {'ACCEPT':>10}")

    # --- Тест 3: проверка кубического роста ---
    print()
    print("=" * 72)
    print("ТЕСТ 3: Проверка кубического роста (worst-case)")
    print("-" * 72)
    print(f"{'n':>5} | {'Шаги':>11} | {'Шаги/n³':>11} | {'Рост шагов':>11} | {'(n/n_prev)³':>11}")
    print("-" * 72)

    for idx, n in enumerate(sizes):
        s = worst_steps[idx]
        r = s / (n ** 3)
        if idx > 0:
            growth = s / worst_steps[idx - 1]
            expected = (n / sizes[idx - 1]) ** 3
            print(f"{n:>5} | {s:>11} | {r:>11.6f} | {growth:>11.2f} | {expected:>11.2f}")
        else:
            print(f"{n:>5} | {s:>11} | {r:>11.6f} | {'—':>11} | {'—':>11}")

    # --- Тест 4: конкретные примеры ---
    print()
    print("=" * 72)
    print("ТЕСТ 4: Конкретные примеры")
    print("-" * 72)

    cases = [
        (
            "Треугольник {0,1,2}",
            3,
            [
                (0, 1),
                (1, 2),
                (0, 2)
            ]
        ),
        (
            "Путь 0-1-2",
            3,
            [
                (0, 1),
                (1, 2)
            ]
        ),
        (
            "Пустой граф (4 верш.)",
            4,
            [

            ]
        ),
        (
            "5 верш., △ на {2,3,4}",
            5,
            [
                (0, 1),
                (2, 3),
                (3, 4),
                (2, 4)
            ]
        ),
        (
            "Тестовый пример",
            5,
            [
                (0, 4),
                (0, 2),
                (0, 3),
                (1, 3)
            ]
        )
    ]
    for name, n, edges in cases:
        adj = [[False]*n for _ in range(n)]
        for u, v in edges:
            adj[u][v] = adj[v][u] = True
        res, s = has_triangle(adj, n)
        print(f"  {name:<25} → {'ACCEPT' if res else 'REJECT'}, шагов: {s}")

    # --- Вывод ---
    print()
    print("=" * 72)
    print("ВЫВОД:")
    print("  Факт. число шагов в worst-case = C(n,3) = n(n-1)(n-2)/6.")
    print("  Отношение шагов/n³ → 1/6 ≈ 0.1667 — подтверждает O(n³).")
    print("  Рост при удвоении n ≈ 8×, что соответствует кубической сложности.")
    print("=" * 72)

    visualization(sizes, worst_steps, worst_theory, worst_times)

if __name__ == "__main__":
    run_tests()