# -*- coding: utf-8 -*-
"""Untitled69.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAI87ot9Z17Kozhu6scQYQOR0RuDCv5D
"""

import time
import random


def verify_half_clique(graph_matrix, certificate):
    """
    Полиномиальный верификатор для языка HALF-CLIQUE.
    :param graph_matrix: Матрица смежности графа G (размер m x m)
    :param certificate: Список вершин (сертификат)
    :return: True, если сертификат доказывает принадлежность, иначе False
    """
    m = len(graph_matrix)

    # 1. Проверка размера сертификата (не менее m/2)
    if len(certificate) < m / 2:
        return False

    # 2. Проверка корректности вершин в сертификате (нет ли дубликатов или неверных индексов)
    # 2.1. Проверка дубликатов
    if len(set(certificate)) != len(certificate):
        return False

    # 2.2. Проверка индексов
    for v in certificate:
        if v < 0 or v >= m:
            return False

    # 3. Проверка того, что все вершины в сертификате попарно соединены (образуют клику)
    cert_size = len(certificate)
    for i in range(cert_size):
        u = certificate[i]
        for j in range(i + 1, cert_size):
            v = certificate[j]
            # Если между какой-то парой вершин нет ребра - это не клика
            if graph_matrix[u][v] == 0:
                return False

    return True


def generate_test_data(m, k):
    """
    Генерирует граф размера m и заведомо правильный сертификат (клику размера m/2)
    для тестирования наихудшего (самого долгого) случая работы верификатора.
    """
    # Инициализация пустой матрицы смежности
    graph = [[0] * m for _ in range(m)]

    # Случайным образом выбираем вершины, которые станут кликой
    certificate = random.sample(range(m), k)

    # Соединяем все вершины сертификата между собой (создаем клику)
    for i in range(len(certificate)):
        for j in range(i + 1, len(certificate)):
            u = certificate[i]
            v = certificate[j]
            graph[u][v] = 1
            graph[v][u] = 1

    return graph, certificate


def sample_test(graph, cert):
    is_valid = verify_half_clique(graph, cert)
    print(f"Матрица смежности:")
    for row in graph:
        print(f"\t", *row)
    print(f"Сертификат: \n\t", *cert)
    print(f"{'Валидный' if is_valid else 'Не валидный'} сертификат для данного графа")
    print()


def custom_tests():
    graph = [
        [0, 1, 1, 0],
        [1, 0, 1, 0],
        [1, 1, 0, 0],
        [0, 0, 0, 0],
    ]
    cert = [0, 1, 2]
    sample_test(graph, cert)

    graph = [
        [0, 1, 1, 0],
        [1, 0, 1, 0],
        [1, 1, 0, 0],
        [0, 0, 0, 0],
    ]
    cert = [0, 1, 3]
    sample_test(graph, cert)


def run_experiments():
    """
    Функция для эмпирической проверки временной сложности O(m^2).
    """
    # Будем удваивать количество вершин графа
    sizes = [100, 200, 400, 800, 1600, 3200, 6400]
    prev_time = None

    print(f"{'Размер графа (m)':<20} | {'Размер серт-та':<15} | {'Время (сек)':<15} | {'Отношение t(m)/t(m/2)':<20}")
    print("-" * 75)

    for m in sizes:
        k = (m + 1) // 2 # Размер клики

        graph, cert = generate_test_data(m, k)

        # Замеряем только время работы самого верификатора
        start_time = time.perf_counter()
        is_valid = verify_half_clique(graph, cert)
        end_time = time.perf_counter()

        # Удостоверимся, что верификатор отработал корректно
        assert is_valid == True

        t = end_time - start_time

        # Вычисляем во сколько раз увеличилось время при увеличении m в 2 раза
        ratio = t / prev_time if prev_time else 0.0
        prev_time = t

        print(f"{m:<20} | {len(cert):<15} | {t:<15.6f} | {ratio:<20.2f}")

    print('\n')

    custom_tests()


if __name__ == "__main__":
    run_experiments()