# -*- coding: utf-8 -*-
"""Untitled72.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiWQ_T1WB7rNNVraPKtG30mJzwqKGJcE
"""

class DFA:
    def __init__(self, states, alphabet, transitions, start_state, accept_states):
        self.states = states
        self.alphabet = alphabet
        self.transitions = transitions  # dict: (state, symbol) -> next_state
        self.start_state = start_state
        self.accept_states = accept_states

def turing_machine_simulation(dfa_encoding):
    """
    Симуляция МТ, проверяющей условие языка A
    """
    # Парсинг кодировки ДКА (упрощённая версия)
    dfa = parse_dfa_encoding(dfa_encoding)

    # Шаг 1: Проверяем, есть ли строка чётной длины, которую принимает ДКА
    # Используем алгоритм поиска в ширину для проверки достижимости

    # Строим граф достижимости для чётных длин
    # Состояние: (текущее_состояние_ДКА, чётность_длины)
    # чётность_длины: 0 - чётная, 1 - нечётная

    visited = dict()
    queue = [(dfa.start_state, 0)]  # Начинаем с пустой строки (длина 0 - чётная)
    visited[(dfa.start_state, 0)] = ['']

    while queue:
        current_state, parity = queue.pop(0)

        # Если достигли принимающего состояния с чётной длиной
        if current_state in dfa.accept_states and parity == 0:
            print("Подходящая строка: ", ''.join(visited[(current_state, parity)]) or "Пустая строка")
            return True  # МТ переходит в q_accept

        # Переходы по всем символам алфавита
        for symbol in dfa.alphabet:
            next_state = dfa.transitions.get((current_state, symbol))
            if next_state is not None:
                new_parity = 1 - parity  # Меняем чётность
                new_state = (next_state, new_parity)

                if new_state not in visited:
                    visited[new_state] = visited[(current_state, parity)] + [symbol]
                    queue.append(new_state)

    return False  # МТ переходит в q_reject

def parse_dfa_encoding(encoding):
    """
    Упрощённый парсер кодировки ДКА
    Формат: "Q={q0,q1,q2};Σ={0,1};δ={(q0,0)->q1,(q0,1)->q0,...};q0;F={q1}"
    """
    # Разбираем кодировку
    parts = encoding.split(';')

    # Извлекаем состояния
    states_str = parts[0][2:]  # Убираем "Q="
    states = set(states_str.strip('{}').split(','))

    # Извлекаем алфавит
    alphabet_str = parts[1][2:]  # Убираем "Σ="
    alphabet = set(alphabet_str.strip('{}').split(','))

    # Извлекаем переходы
    transitions_str = parts[2][2:]  # Убираем "δ="
    transitions = {}
    transitions_parts = transitions_str.strip('{}').split(', ')

    for trans in transitions_parts:
        if not trans:
            continue
        trans = trans.strip('()')
        left, right = trans.split(')->')
        state, symbol = left.split(',')
        state = state.strip()
        symbol = symbol.strip()
        transitions[(state, symbol)] = right.strip()

    # Стартовое состояние
    start_state = parts[3].strip()

    # Принимающие состояния
    accept_str = parts[4][2:]  # Убираем "F="
    accept_states = set(accept_str.strip('{}').split(','))

    return DFA(states, alphabet, transitions, start_state, accept_states)

# Тестирование
def turing_machine():
    dfa_encoding = [
        {
            "dfa": "Q={q0,q1};Σ={0,1};δ={(q0,0)->q1, (q0,1)->q1, (q1,0)->q0, (q1,1)->q0};q0;F={q0}",
            "description": "ДКА, который принимает строки чётной длины",
            "expected": True,
        },
        {
            "dfa": "Q={q0,q1};Σ={0,1};δ={(q0,0)->q1, (q0,1)->q1, (q1,0)->q0, (q1,1)->q0};q0;F={q1}",
            "description": "ДКА, который принимает только строки нечётной длины",
            "expected": False,
        },
        {
            "dfa": "Q={q0};Σ={0,1};δ={(q0,0)->q0, (q0,1)->q0};q0;F={q0}",
            "description": "ДКА, который принимает все строки",
            "expected": True,
        },
        {
            "dfa": "Q={q0};Σ={0,1};δ={(q0,0)->q0, (q0,1)->q0};q0;F={}",
            "description": "ДКА, который не принимает ничего",
            "expected": False,
        },
        {
            "dfa": "Q={q0,q1};Σ={0,1};δ={(q0,0)->q0, (q0,1)->q1, (q1,0)->q1, (q1,1)->q0};q0;F={q1}",
            "description": "ДКА, который принимает строки с нечётным количеством единиц",
            "expected": True,  # Принимает строки чётной длины? НЕТ, проверяем:
        },
        {
            "dfa": "Q={q0,q1,q2,q3,q4,q5,q6};Σ={0,1};δ={(q0,0)->q1, (q0,1)->q1, (q1,0)->q2, (q1,1)->q2, (q2,0)->q3, (q2,1)->q3, (q3,0)->q4, (q3,1)->q4, (q4,0)->q6, (q4,1)->q5, (q5,0)->q5, (q5,1)->q5, (q6,0)->q6, (q6,1)->q6};q0;F={q5}",
            "description": "ДКА, который принимает строки с 1 на 5й позиции",
            "expected": True,  # Проверяем:
        },
        {
            "dfa": "Q={q0,q1,q2,q3,q4,q5};Σ={0,1};δ={(q0,0)->q1, (q0,1)->q1, (q1,0)->q2, (q1,1)->q2, (q2,0)->q3, (q2,1)->q3, (q3,0)->q5, (q3,1)->q4, (q4,0)->q4, (q4,1)->q4, (q5,0)->q5, (q5,1)->q5};q0;F={q4}",
            "description": "ДКА, который принимает строки с 1 на 4й позиции",
            "expected": True,
        }
    ]

    for test_number in range(len(dfa_encoding)):
        print("-" * 20)

        example = dfa_encoding[test_number]
        dfa = example["dfa"]
        print(f"ДКА: {dfa}")
        description = example["description"]
        expected = example["expected"]

        print(description)
        print(f"Ожидается: {expected}")

        result = turing_machine_simulation(dfa)

        print(f"Получено: {result}")

if __name__ == "__main__":
    turing_machine()