# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwTt61yJmQ2czS36uZ6Gzh4gU-OgXmWA

# Стоит ли сегодня гулять?

## Задача

Дан размеченный датасет с описанием погоды: температура, солнечность, скорость ветра, наличие дождь. Отвечаем на вопрос "можно ли идти гулять?".

## Реализация

### Импорт библиотек
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score

import tensorflow as tf
from tensorflow import keras

import torch
import torch.nn as nn
import torch.optim as optim

"""### Загрузка данных и первичный анализ"""

weather_df = pd.read_csv('/weather.csv', sep=";")
weather_df

# Переименуем признаки
mapper = {
    "Солнечно": "is_sunny",
    "Температура воздуха": "temperature",
    "Скорость ветра": "wind_speed",
    "Дождь": "is_rainy",
    "Гулять?": "walk"
}
weather_df.columns = pd.Index(map(lambda col_name: mapper[col_name] if col_name in mapper else col_name, weather_df.columns))
weather_df

weather_df.info()

weather_df.describe()

train_features = weather_df.iloc[:, :-1]
target_feature = weather_df.iloc[:, -1]
target_col = target_feature.name

sns.histplot(data=weather_df, x=target_feature.name, hue=target_feature.name, kde=False, element="step")
plt.show()

for col_name in train_features.columns:
  sns.histplot(data=weather_df, x=col_name, hue=target_feature.name, kde=False, element="step")
  plt.show()

sns.boxplot(weather_df["temperature"])
plt.show()
sns.histplot(weather_df["temperature"], bins=20)
plt.show()

"""### Предобработка данных"""

scaler = MinMaxScaler()

weather_df = pd.DataFrame(scaler.fit_transform(weather_df), columns=weather_df.columns)
weather_df[target_col] = weather_df[target_col].astype(int)

weather_df.describe()

X_train, X_test, y_train, y_test = train_test_split(train_features, target_feature, test_size=0.2)

"""### Построение и обучение моделей"""

neurons_on_hidden = [10, 5]

def custom_evaluation(y_test, y_pred):
  print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
  print(f'Precision: {precision_score(y_test, y_pred)}')
  print(f'Recall: {recall_score(y_test, y_pred)}')
  print(f'F1: {f1_score(y_test, y_pred)}')

  fig, ax = plt.subplots(figsize=(4, 3))
  sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, cmap="Greens", ax=ax)
  ax.set_xlabel('Предсказанные')
  ax.set_ylabel('Истинные')
  ax.set_title('Матрица ошибок')
  plt.show()

"""#### Scikit learn"""

mlp = MLPClassifier(hidden_layer_sizes=neurons_on_hidden, max_iter=1000)
mlp.fit(X_train, y_train)

y_pred = mlp.predict(X_test)
custom_evaluation(y_test, y_pred)

"""#### TensorFlow"""

model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)),
    keras.layers.Dense(neurons_on_hidden[0], activation='relu'),
    keras.layers.Dense(neurons_on_hidden[1], activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model_history = model.fit(X_train, y_train, epochs=1000, batch_size=100, verbose=0)

y_pred_proba = model.predict(X_test).flatten()
y_pred = (y_pred_proba > 0.5).astype(int)
custom_evaluation(y_test, y_pred)

plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 1)
plt.plot(model_history.history['loss'], label='train loss')
plt.title('Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(model_history.history['accuracy'], label='train acc')
plt.title('Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""#### PyTorch"""

X_train_torch = torch.tensor(X_train.values, dtype=torch.float32)
y_train_torch = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
X_test_torch = torch.tensor(X_test.values, dtype=torch.float32)
y_test_torch = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

class BinaryMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(X_train.shape[1], neurons_on_hidden[0]),
            nn.ReLU(),
            nn.Linear(neurons_on_hidden[0], neurons_on_hidden[1]),
            nn.ReLU(),
            nn.Linear(neurons_on_hidden[1], 1),
            nn.Sigmoid()
        )
    def forward(self, x):
        return self.net(x)

model = BinaryMLP()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(1000):
    y_pred = model(X_train_torch)
    loss = criterion(y_pred, y_train_torch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.no_grad():
    probs = model(X_test_torch)
    y_pred = (probs > 0.5).int().view(-1).numpy()

custom_evaluation(y_test, y_pred)

"""## Вывод

Наиболее качественно работал классификатор на PyTorch, наиболее стабильный результат дает модель scikit learn так как можно явно указать seed (random_state)

# Fashion MNIST

## Задача

На базе классических нейронных сетей и библиотеки TensorFlow построить классификатор для данных из набора Fashion-MNIST

## Импорт библиотек
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

"""## Загрузка и предобработка данных"""

# Загрузка данных
(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

# Нормализация: пиксели от [0..255] → [0..1]
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Развёртка изображений в векторы (28×28 → 784)
x_train = x_train.reshape(x_train.shape[0], 28 * 28)
x_test = x_test.reshape(x_test.shape[0], 28 * 28)

print(f"Тренировочных образцов: {x_train.shape[0]}")
print(f"Тестовых образцов: {x_test.shape[0]}")
print(f"Размер входа: {x_train.shape[1]}")

"""## Построение модели"""

model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(784,)),
    keras.layers.Dropout(0.2), # Регуляризация
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""## Обучение модели"""

history = model.fit(
    x_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""## Визуализация результатов"""

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Точность (тренировка)')
plt.plot(history.history['val_accuracy'], label='Точность (валидация)')
plt.title('Точность модели')
plt.xlabel('Эпоха')
plt.ylabel('Точность')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Потеря (тренировка)')
plt.plot(history.history['val_loss'], label='Потеря (валидация)')
plt.title('Потеря модели')
plt.xlabel('Эпоха')
plt.ylabel('Потеря')
plt.legend()

plt.show()

"""## Проверка модели"""

predictions = model.predict(x_test[:5])
predicted_classes = np.argmax(predictions, axis=1)

class_names = [
    'T‑shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
    'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot'
]

for i in range(5):
    plt.figure(figsize=(10, 4))
    plt.imshow(x_test[i].reshape(28, 28), cmap='gray')
    plt.title(f"Предсказано: {class_names[predicted_classes[i]]}")
    plt.axis('off')
    plt.show()

