# -*- coding: utf-8 -*-
"""ЛР4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwdvUfuWJLyY9B7ljKvewifZYizYgVct

# Классификация риса (арборио и басмати)
"""

!pip install split-folders
!pip install torchview

import os
import shutil
import numpy as np
import random
from PIL import Image
import splitfolders

import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator    # Генератор обучающих данных
from tensorflow.keras.models import Sequential      # Контейнер модели
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense  # Типы используемых слоев
from tensorflow.keras.optimizers import Adam    # Алгоритм оптимизации
import matplotlib.pyplot as plt
from zipfile import ZipFile

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, TensorDataset
from torch.nn import Dropout, BatchNorm2d
from tqdm import tqdm
from torchview import draw_graph

IMG_HEIGHT, IMG_WIDTH = 150, 150
BATCH_SIZE = 64
NUM_EPOCHS = 30

zip_path = '/content/drive/MyDrive/Rice_arborio_vs_basmati.zip'
dataset_dir = r'/content/3. Rice - arborio vs basmati'

with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()

print(f"Arborio images count = {len(os.listdir(os.path.join(dataset_dir, 'Arborio')))}")
print(f"Basmati images count = {len(os.listdir(os.path.join(dataset_dir, 'Basmati')))}")

plt.imshow(Image.open(os.path.join(dataset_dir, 'Arborio', 'Arborio (1).jpg')))
plt.show()

plt.imshow(Image.open(os.path.join(dataset_dir, 'Basmati', 'Basmati (1).jpg')))
plt.show()

splitfolders.ratio(
    f"{dataset_dir}",
    output=f"{dataset_dir}-split",
    seed=42,
    ratio=(0.6, 0.2, 0.2),
    group_prefix=None
)

"""## TensorFlow

### Предобработка данных
"""

# Аугментация для тренировочных данных. Помогает модели выделять устойчивые признаки
train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255, # Нормирование
    rotation_range=20, # Вращение на случайный угол до 20 градусов
    width_shift_range=0.2, # Случайный сдвиг по ширине до 20%
    height_shift_range=0.2, # Случайный сдвиг по высоте до 20%
    horizontal_flip=True, # Случайное горизонтальное отражение
    zoom_range=0.2, # Случайный зум до 20%
    shear_range=0.2,
    fill_mode='nearest' # Заполнение пустых мест ближайшими пикселями
)

# Только рескейлинг для валидации и теста
val_test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

# Генераторы данных. Загрузка и аугментация данных во время работы
train_generator = train_datagen.flow_from_directory(
    f"{dataset_dir}-split/train",
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=True
)

validation_generator = val_test_datagen.flow_from_directory(
    f"{dataset_dir}-split/val",
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=True
)

test_generator = val_test_datagen.flow_from_directory(
    f"{dataset_dir}-split/test",
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

print(f"Классы: {train_generator.class_indices}")
print(f"Размер тренировочной выборки: {train_generator.samples}")
print(f"Размер валидационной выборки: {validation_generator.samples}")
print(f"Размер тестовой выборки: {test_generator.samples}")

"""### Построение и обучение модели"""

model = tf.keras.Sequential([
  # Слой 1: 32 фильтра, ядро 3x3
  tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
  tf.keras.layers.MaxPooling2D((2, 2)),

  # Слой 2: 64 фильтра, ядро 3x3
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D((2, 2)),

  # Слой 3: 128 фильтров, ядро 3x3
  tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D((2, 2)),

  # Переход к полносвязным слоям
  tf.keras.layers.Flatten(),

  # Полносвязный слой 1: 64 нейрона
  tf.keras.layers.Dense(64, activation='relu'),

  # Полносвязный слой 2: 128 нейронов
  tf.keras.layers.Dense(128, activation='relu'),

  # Выходной слой: 2 класса
  tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.RMSprop(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

model_history = model.fit(
    train_generator,
    epochs=NUM_EPOCHS,
    validation_data=validation_generator,
    callbacks=[
        tf.keras.callbacks.ModelCheckpoint(
            filepath='models/best_custom_model.h5',
            save_best_only=True,
            monitor='val_loss',
            verbose=1
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=10,
            restore_best_weights=True,
            verbose=1
        )
    ],
    verbose=1
)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(model_history.history['loss'], label='Training Loss')
plt.plot(model_history.history['val_loss'], label='Validation Loss')
plt.title('Функция потерь')
plt.xlabel('Эпохи')
plt.ylabel('Потери')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(model_history.history['accuracy'], label='Training Accuracy')
plt.plot(model_history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Точность')
plt.xlabel('Эпохи')
plt.ylabel('Точность')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()

test_images, test_labels = next(test_generator)
num_demo = min(10, BATCH_SIZE)

for i in range(num_demo):
  image = test_images[i]
  true_label = "арборио" if test_labels[i] == 0 else "басмати"

  prediction = model.predict(np.expand_dims(image, axis=0), verbose=0)[0][0]

  predicted_class = "арборио" if prediction < 0.5 else "басмати"

  plt.subplot(1, num_demo, i + 1)
  plt.imshow(image)
  plt.title(f'Истина: {true_label}\nПредсказание: {predicted_class}')
  plt.axis('off')
  plt.show()

"""## PyTorch"""

transforms_train = transforms.Compose([
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

transforms_test = transforms.Compose([
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Создаем датасеты
dataset_train = datasets.ImageFolder(f"{dataset_dir}-split/train", transforms_train)
dataset_val = datasets.ImageFolder(f"{dataset_dir}-split/val", transforms_train)
dataset_test = datasets.ImageFolder(f"{dataset_dir}-split/test", transforms_test)

dataloader_train = DataLoader(dataset_train, batch_size=32, shuffle=True, num_workers=2)
dataloader_val = DataLoader(dataset_val, batch_size=32, shuffle=True, num_workers=2)
dataloader_test = DataLoader(dataset_test, batch_size=32, shuffle=False, num_workers=2)

# Get dataset sizes and class names
dataset_sizes_train = len(dataset_train)
dataset_sizes_val = len(dataset_val)
dataset_sizes_test = len(dataset_test)
class_names = dataset_train.classes
print(f"Classes: {class_names}")
print(f"Dataset sizes: {dataset_sizes_train}, {dataset_sizes_val}, {dataset_sizes_test}")

class RiceCNN(nn.Module):
    def __init__(self):
        super(RiceCNN, self).__init__()
        self.nn = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(2048, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        out = self.nn(x)
        return out

model_pt = RiceCNN()

criterion = nn.BCEWithLogitsLoss()

LEARNING_RATE_PT = 0.00005
optimizer = optim.Adam(model_pt.parameters(), lr=LEARNING_RATE_PT)

def train_one_epoch(model, epoch, train_data_loader, test_data_loader, optimizer, criterion, device):
    model.train()
    total_loss, correct, test_total_loss, test_correct = 0, 0, 0, 0
    progress_bar = tqdm(train_data_loader, desc=f"Epoch {epoch}", leave=False)
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels.float().unsqueeze(1))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        predicted = (torch.sigmoid(outputs) > 0.5).float()
        correct += (predicted == labels.float().unsqueeze(1)).sum().item()

        progress_bar.set_postfix_str(f"Loss: {total_loss / len(train_data_loader):.4f}, Accuracy: {correct / len(train_data_loader.dataset):.4f}")

    model.eval()
    with torch.no_grad():
        for images, labels in test_data_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels.float().unsqueeze(1))

            test_total_loss += loss.item()
            predicted = (torch.sigmoid(outputs) > 0.5).float()
            test_correct += (predicted == labels.float().unsqueeze(1)).sum().item()

    train_loss = total_loss / len(train_data_loader)
    train_accuracy = correct / len(train_data_loader.dataset)
    test_loss = test_total_loss / len(test_data_loader)
    test_accuracy = test_correct / len(test_data_loader.dataset)
    return train_loss, train_accuracy, test_loss, test_accuracy

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
model_pt.to(device)

history = {"loss": [], "val_loss": [], "accuracy": [], "val_accuracy": []}

for epoch in range(NUM_EPOCHS):
    train_loss, accuracy, val_loss, val_accuracy = train_one_epoch(model_pt, epoch, dataloader_train, dataloader_test, optimizer, criterion, device)
    history["loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["accuracy"].append(accuracy)
    history["val_accuracy"].append(val_accuracy)
    print(f"\nEpoch {epoch+1}/{NUM_EPOCHS}, Loss: {train_loss:.4f}, Accuracy: {accuracy:.4f}, Test Loss: {val_loss:.4f}, Test Accuracy: {val_accuracy:.4f}")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history['loss'], label='Training Loss')
plt.plot(history['val_loss'], label='Validation Loss')
plt.title('Функция потерь')
plt.xlabel('Эпохи')
plt.ylabel('Потери')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(history['accuracy'], label='Training Accuracy')
plt.plot(history['val_accuracy'], label='Validation Accuracy')
plt.title('Точность')
plt.xlabel('Эпохи')
plt.ylabel('Точность')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()

